# Generated by Django 4.1.7 on 2023-03-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=225)),
                ('cat_image', models.ImageField(blank=True, upload_to='img/categories')),
            ],
        ),
    ]
