# Generated by Django 4.1.7 on 2023-04-19 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='name',
        ),
        migrations.AddField(
            model_name='address',
            name='address_1',
            field=models.CharField(default=datetime.datetime(2023, 4, 19, 13, 27, 54, 155609), max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2023, 4, 19, 13, 27, 54, 155609), max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2023, 4, 19, 13, 27, 54, 155609), max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default=datetime.datetime(2023, 4, 19, 13, 27, 54, 155609), max_length=15),
        ),
    ]
